[package]
name = "exchange"
version = "0.0.1"
authors = ["james <james@calculated.fi>"]
edition = "2021"

exclude = []

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
cw20 = { workspace = true }
